---
- name: Configuring a Tomcat directory
  file:
    path: /opt/tomcat9
    owner: tomcat
    group: tomcat
    mode: 755
    recurse: yes

- name: Download tomcat package
  get_url: 
    url: "{{tomcat_download_url}}"
    dest: "{{tomcat_download_location}}"
    remote_src: yes

- name: Extract tomcat packages
  unarchive: 
    src: /opt/tomcat9/apache-tomcat-9.0.64.tar.gz
    dest: "{{tomcat_download_location}}"
    remote_src: yes
 
- name: Changing ownership of tomcat directory
  file:
    path: "{{tomcat_download_location}}"
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o+rx"
    recurse: yes
    state: directory
 
- name: Copy tomcat.service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: Start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"
