---
#ansy playbook start with three dash
-
###this minus in yaml indicate a list of items. the play contains a list of play
  hosts: [nodes]
  vars:
    motd_ubuntu: "Hi Amit, welcome to ubuntu linux machine\n"
    motd_redhat: "Hi Amit, Welcome to RedHat linux machine\n"
  
  tasks:
    - name: configure a motd message of the day in redhat
      copy:
        content: "{{motd_ubuntu}}"
        dest: /etc/motd
      notify: MOTD change in "Ubuntu"
      when: ansible_distribution=="Ubuntu"

    - name: configure a motd message of the day in redhat
      copy:
        content: "{{motd_redhat}}"
        dest: /etc/motd
      notify: MOTD change in "RedHat"
      when: ansible_distribution=="RedHat"

  handlers:
    - name: MOTD change in "Ubuntu"
      debug:
        msg: The Motd has changed in ubuntu
    - name: MOTD change in "RedHat"
      debug:
        msg: The Motd has changed in redhat
