---
#ansy playbook start with three dash
-
###this minus in yaml indicate a list of items. the play contains a list of play
  hosts: [nodes]
  vars:
    motd_redhat: "welcome to redhat linux\n"
    motd_ubuntu: "welcome to ubuntu linux \n"
  
  tasks:
    - name: install epel release 
    #epel enterprise linux it is being specially created for redhat based system
      dnf: 
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        update_cache: yes
        state: present #present or absent
      when: ansible_distribution == "RedHat"

    - name: install nginx
      package: 
      #this module autmatically identify the os and run the installation command accoring to your os
        name: nginx 
        state: latest

    - name: install patch
      yum: 
        name: patch 
        update_cache: yes
        state: latest
      when: ansible_distribution == "RedHat"

    - name: patch the nginx.conf include site-availability , default server entry
      patch: #this patch module has root privilage
        src: files/nginx.conf.redhat.patch
        dest: /etc/nginx/nginx.conf
      when: ansible_distribution == "RedHat"

    - name: create a directory /etc/nginx/sites-available 
      file: 
        path: /etc/nginx/sites-available
        state: directory 

    - name: create a directory /etc/nginx/sites-enabled
      file: 
        path: /etc/nginx/sites-enabled 
        state: directory

    - name: copy the default nginx configuration
      copy:
        src: files/nginx-default.conf
        dest: /etc/nginx/sites-available/default

    - name: create a symbolic link /etc/nginx/sites-available/default to /etc/nginx/sites-enablehd/default
      file: 
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default 
        state: link

    - name: we will create push our own file using jinja 2 template
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
      
    - name: restart nginx server
      service:
      #systemctl restart httpd service
        name: nginx 
        state: restarted
      notify: check http service 

    - name: add port in firewalld
    #by default when you install redhat it get installed with firewalld a inbuilt firewall in your redhat based system
      firewalld:
        service: http 
        permanent: true 
        state: enabled 
      when: ansible_distribution == "RedHat"
      notify: Reload Firewalld 

  handlers:
    - name: check http service
      uri: 
        url: http://{{ ansible_default_ipv4.address }}
        #gather fact module
        status_code: 200
    - name: Reload Firewalld
      service:
        name: firewalld
        state: reloaded
